### ISSUE TITLE
[SIN] Add your best projects in the project directory

### ISSUE THREAD

**Issue by AjayKhalsa** [CMPN-CODECELL/Hacktoberfest2020#11]
Share your best scripts, projects, games, etc the repository

**Comment by vivektamore** [comment]
https://github.com/phoboslab/jsmpeg-vnc/pull/70/commits/105998600c0ae2ca6b8920194f5698c486008db7

**Comment by vivektamore** [comment]
Yess....

**Comment by McTechie** [comment]
Added json-server #57

**Comment by aritrochakraborty29** [comment]
Can you please assign me.?

**Comment by ghost** [comment]
Hi can you assign me this for hacktoberfest? thank!

**Comment by ghost** [comment]
Hi just added a project using js, plz check. thanks!
