### ISSUE TITLE
Add Sorting Algorithms[EXE]

### ISSUE THREAD

**Issue by rohan527** [CMPN-CODECELL/Hacktoberfest2020#14]
Add a sorting algorithm in any language of your choice :v:

**Comment by darshmgandhi** [comment]
@rohan527  I want to add Counting Sort. Please Assign this to me.

**Comment by darshmgandhi** [comment]
Added a sorting algorithm. Counting Sort. Please review my PR #15 . Thank you. Implemented in Java. I have kept the input range as [1, 100000]

**Comment by thewires2** [comment]
@mcs-codes please dont link the issue , we want other participants to get a chance too

**Comment by the-wrong-guy** [comment]
Is there is any limit on how much I can add algorithms!!

**Comment by the-wrong-guy** [comment]
> Add a sorting algorithm in any language of your choice ✌️

Is there is any limit on how much algorithms i can add and will count as PR in hacktoberfest!!

**Comment by sarthak-1503** [comment]
@rohan527 Can you assign this issue to me?

**Comment by rohan527** [comment]
> > Add a sorting algorithm in any language of your choice v
> 
> Is there is any limit on how much algorithms i can add and will count as PR in hacktoberfest!!

No there isn't a limit to the number of algorithms you can add. However please try adding new algorithms so as to help others. Thank you!

**Comment by sarthak-1503** [comment]
@rohan527 Please review my pull request #73

**Comment by sarthak-1503** [comment]
@rohan527 Please review my pull request #74

**Comment by JukMR** [comment]
Hi! I would like to implement an Insertion Sort algorithm in Python. Could I do that? I couldn't find any previous implementation of it. Thanks in advance! :)

**Comment by JukMR** [comment]
> Hi! I would like to implement an Insertion Sort algorithm in Python. Could I do that? I couldn't find any previous implementation of it. Thanks in advance! :)

I implemented the HeapSort sorting algorithm instead because I thought somebody made a PR about it in #69. Hopes this still count as a valid PR!
