### ISSUE TITLE
[SIN] Using Flask and Python create a api to pull this repository's hacktoberfest statistics

### ISSUE THREAD

**Issue by mm-git01** [CMPN-CODECELL/Hacktoberfest2020#16]
Create a script that will store the no of pr's,issues generated during hacktober fest on this repo in a csv file and then create a API that anyone can call to fetch that csv file.

**Comment by RitikMody** [comment]
I am interested in doing this , do you just want the numbers or even the titles? @Pac23

**Comment by RitikMody** [comment]
And please assign it to me @Pac23 @thewires2

**Comment by mm-git01** [comment]
> I am interested in doing this , do you just want the numbers or even the titles? @Pac23

Titles,Author,No,Date,Time,flair Also let me know your shipping address if you complete this i will send you some GitHub Stickers as a additional prize.

**Comment by RitikMody** [comment]
![image](https://user-images.githubusercontent.com/47336724/94991125-7c1a4480-059e-11eb-9bb8-94fab54bc5d0.png)
Is this fine? @Pac23  @thewires2

**Comment by thewires2** [comment]
Looks good, go ahead

**Comment by mm-git01** [comment]
> ![image](https://user-images.githubusercontent.com/47336724/94991125-7c1a4480-059e-11eb-9bb8-94fab54bc5d0.png)
> Is this fine? @Pac23 @thewires2

this looks good
